name: fp_growth
description: A high-performance Dart FP-Growth algorithm for frequent pattern mining and association rule learning, with CLI and CSV support.
version: 1.0.2
repository: https://github.com/MostafaSensei106/FP-Growth
homepage: https://github.com/MostafaSensei106/FP-Growth

license: GPL-3.0-or-later
topics:
  [
    fp-growth,
    dart,
    algorithm,
    frequent-pattern-mining,
    association-rule-learning,
  ]

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  args: ^2.3.1

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
