name: fp_growth
description: A high-performance Dart implementation of the FP-Growth algorithm for frequent pattern mining and association rule learning. Features advanced metrics, a command-line interface, and CSV support.
version: 1.0.1
repository: https://github.com/MostafaSensei106/FP-Growth
homepage: https://github.com/MostafaSensei106/FP-Growth

license: GPL-3.0-or-later
topics:
  [
    dart-cli,
    data-mining-algorithm,
    fp-growth,
    performance,
    algorithm,
    flutter,
    dart,
    frequent-pattern-mining,
    association-rule-learning,
    csv-processing,
    command-line-tool,
    analytics,
    machine-learning,
  ]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  args: ^2.3.1

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
